apiVersion: v1
kind: ConfigMap
metadata:
  name: users-api-config
  labels:
    app: fiap-cloud-games-users
data:
  ASPNETCORE_ENVIRONMENT: "Devlopment"
  ServiceBus__UseWebSockets: "false"
  Elasticsearch__IndexName: "users"
  Elasticsearch__Uri: "http://20.206.68.98:9200"
