apiVersion: v1
kind: Service
metadata:
  name: fiap-cloud-games-users
  labels:
    app: fiap-cloud-games-users
spec:
  type: LoadBalancer
  selector:
    app: fiap-cloud-games-users
  ports:
    - name: http
      port: 8083
      targetPort: 80
